name: Bug
description: 不具合の報告
title: "[Bug] "
labels: ["type:bug", "status:backlog"]
body:
  - type: input
    id: related_story
    attributes:
      label: Related User Story ID
      description: 関連する User Story（不明なら空欄可）
      placeholder: US-XXX
    validations:
      required: false

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: 再現手順
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
